FEATURE: Support for CSS-like id selector
sitegeist/Sitegeist.Slipstream pull request #25
Opened 2024-02-08 15:25 UTC by jonnitto

In some enviroments, it is not as easy to get the id selector correctly written. This add the support for writing the selector for an id in a simple CSS alike way

2024-02-08 17:14 UTC, mficzel commented
I dislike the switch between xpath and selectors but get your reasoning?

how about a breaking release and switch entirely to css selectors? In all cases I know we always streamed to the head anyways and never changed the default.

2024-02-08 19:08 UTC, jonnitto commented
If we switch entirely, we would have to include a dependency or a lot more code. Or we just say, you can select `id` or tags…

2025-08-04 14:52 UTC, mficzel approved these changes

2025-08-04 14:56 UTC, mficzel requested changes
I agree to this when a Testcase is added to the SlipstreamServiceTest

2025-08-04 17:55 UTC, jonnitto commented
I removed the automatic tag selector, as it can happen someone uses a complex XPATH. But I added a class name selector, as this is kind of complicated to write. I also improve the id selector and explained it in the readme.

I also add tests for after and before location processing in SlipStreamService

2025-08-05 11:48 UTC, mficzel approved these changes

2025-08-05 11:48 UTC, merged